# Generated by Django 4.2.3 on 2023-09-19 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='BinBooking',
            fields=[
                ('house_number', models.CharField(max_length=50)),
                ('landmark', models.CharField(default=None, max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('bin_size', models.CharField(max_length=20)),
                ('bin_capacity', models.CharField(max_length=20)),
                ('collection_period', models.CharField(default=None, max_length=20)),
                ('booking_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app32.bin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinEvent',
            fields=[
                ('bin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bin_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('event_id', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('category1', 'Environmental Cleanup Campaign'), ('category2', 'Waste Management Seminar'), ('category3', 'Expo'), ('category4', 'Composting Workshop'), ('category5', 'Environmental Hackathon')], default=None, max_length=50)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=255)),
                ('mobile_number', models.CharField(default='None', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('booking_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('attendees', models.PositiveIntegerField()),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app32.event')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookedBinStatus',
            fields=[
                ('status_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fill_level', models.PositiveIntegerField(choices=[(20, '20%'), (40, '40%'), (50, '50%'), (70, '70%'), (90, '90%')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='app32.binbooking')),
            ],
        ),
    ]
