# Generated by Django 4.2.3 on 2023-08-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_of_contact',
        ),
    ]
