# Generated by Django 4.2.3 on 2023-09-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0002_wastecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
