# Generated by Django 4.2.3 on 2023-08-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0002_rename_phone_number_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
