# Generated by Django 4.2.3 on 2023-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0003_alter_wastecollection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollection',
            name='datestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
