# Generated by Django 4.2.3 on 2023-09-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0004_wastecollection_datestamp_wastecollection_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedbinstatus',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
