# Generated by Django 4.2.3 on 2023-09-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0005_alter_bookedbinstatus_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinBookingEvent',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date_time', models.DateTimeField()),
                ('event_location', models.CharField(max_length=255)),
                ('estimated_attendees', models.PositiveIntegerField()),
                ('event_duration', models.CharField(max_length=50)),
                ('rental_start_date', models.DateField()),
                ('rental_end_date', models.DateField()),
                ('delivery_time', models.DateTimeField()),
                ('pickup_time', models.DateTimeField()),
                ('number_of_bins_needed', models.PositiveIntegerField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app32.binevent')),
            ],
        ),
    ]
