# Generated by Django 4.2.3 on 2023-09-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0006_binbookingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binbookingevent',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='binbookingevent',
            name='rental_end_date',
        ),
        migrations.RemoveField(
            model_name='binbookingevent',
            name='rental_start_date',
        ),
    ]
