# Generated by Django 4.2.3 on 2023-09-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0007_remove_binbookingevent_event_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binbookingevent',
            name='estimated_attendees',
        ),
    ]
