# Generated by Django 4.2.3 on 2023-08-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0008_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
