# Generated by Django 4.2.3 on 2023-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0010_rename_payment_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedbinstatus',
            name='fill_level',
            field=models.PositiveIntegerField(choices=[(20, '20%'), (40, '40%'), (50, '50%'), (70, '70%'), (90, '90%')], null=True),
        ),
    ]
