# Generated by Django 4.2.3 on 2023-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0011_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('attendees', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
