# Generated by Django 4.2.3 on 2023-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0011_alter_bookedbinstatus_fill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='number_of_bins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
