# Generated by Django 4.2.3 on 2023-08-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0012_enrollment_delete_eventregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='EventEnrollment',
        ),
    ]
