# Generated by Django 4.2.3 on 2023-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0012_bin_number_of_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='binevent',
            name='number_of_bins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
