# Generated by Django 4.2.3 on 2023-08-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0013_rename_enrollment_eventenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventenrollment',
            name='gender',
        ),
    ]
