# Generated by Django 4.2.3 on 2023-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0015_eventregistration_delete_eventenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
