# Generated by Django 4.2.3 on 2023-08-28 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app32', '0016_remove_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app32.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
