# Generated by Django 4.2.3 on 2023-08-28 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0017_remove_eventregistration_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
