# Generated by Django 4.2.3 on 2023-10-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0017_rename_amount_paid_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
