# Generated by Django 4.2.3 on 2023-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0018_userprofile_subscription_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
