# Generated by Django 4.2.3 on 2023-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0018_remove_event_id_event_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
