# Generated by Django 4.2.3 on 2023-08-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0019_alter_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
