# Generated by Django 4.2.3 on 2024-03-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0021_supercoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercoin',
            name='coins',
            field=models.IntegerField(default=300),
        ),
    ]
