# Generated by Django 4.2.3 on 2023-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0021_rename_title_event_name_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
