# Generated by Django 4.2.3 on 2023-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0022_remove_event_event_id_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
