# Generated by Django 4.2.3 on 2024-03-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0023_alter_supercoin_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supercoin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app32.supercoin'),
        ),
        migrations.AlterField(
            model_name='supercoin',
            name='coins',
            field=models.IntegerField(default=300),
        ),
    ]
