# Generated by Django 4.2.3 on 2024-03-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0024_userprofile_supercoin_alter_supercoin_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
