# Generated by Django 4.2.3 on 2023-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0024_bin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinEvent',
            fields=[
                ('bin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bin',
            name='image',
        ),
    ]
