# Generated by Django 4.2.3 on 2023-08-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0025_binevent_remove_bin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bin_images/'),
        ),
        migrations.AddField(
            model_name='binevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bin_images/'),
        ),
    ]
