# Generated by Django 4.2.3 on 2023-08-30 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app32', '0026_bin_image_binevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.CreateModel(
            name='BinBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('house_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=10)),
                ('bin_size', models.CharField(max_length=20)),
                ('bin_capacity', models.CharField(max_length=20)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app32.bin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
