# Generated by Django 4.2.3 on 2023-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0029_remove_binbooking_booking_id_binbooking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.PositiveIntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
