# Generated by Django 4.2.3 on 2023-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0030_remove_event_id_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
