# Generated by Django 4.2.3 on 2023-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0031_alter_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='Event_id',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
