# Generated by Django 4.2.3 on 2023-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0032_remove_event_event_id_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
