# Generated by Django 4.2.3 on 2023-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0037_userprofile_mobile_number_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
