# Generated by Django 4.2.3 on 2023-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0040_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
