# Generated by Django 4.2.3 on 2023-09-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0041_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
    ]
