# Generated by Django 4.2.3 on 2023-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0043_userprofile_mobile_number_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
