# Generated by Django 4.2.3 on 2023-09-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0045_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Event_id',
            new_name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('category1', 'Environmental Cleanup Campaign'), ('category2', 'Waste Management Seminar'), ('category3', 'Expo'), ('category4', 'Composting Workshop'), ('category5', 'Environmental Hackathon')], default=None, max_length=50),
        ),
    ]
