# Generated by Django 4.2.3 on 2023-09-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0046_rename_event_id_event_event_id_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='phone_number',
        ),
    ]
