# Generated by Django 4.2.3 on 2023-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0047_remove_eventbooking_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
