# Generated by Django 4.2.3 on 2023-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0048_event_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(default=0),
        ),
    ]
