# Generated by Django 4.2.3 on 2023-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0049_alter_event_max_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binbooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='binbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='binbooking',
            name='phone',
        ),
        migrations.AddField(
            model_name='binbooking',
            name='collection_period',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='binbooking',
            name='landmark',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='binbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
