# Generated by Django 4.2.3 on 2023-09-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0051_binbooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binbooking',
            name='booking_id',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
    ]
