# Generated by Django 4.2.3 on 2023-09-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0052_alter_binbooking_booking_id_binstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinStatus',
            new_name='BinStatuss',
        ),
    ]
