# Generated by Django 4.2.3 on 2023-09-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0053_binstatus_timestamp_alter_binstatus_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binbooking',
            name='booking_id',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='binstatus',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app32.binbooking', to_field='booking_id'),
        ),
    ]
