# Generated by Django 4.2.3 on 2023-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0054_alter_binbooking_booking_id_alter_binstatus_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binstatus',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
