# Generated by Django 4.2.3 on 2023-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0054_alter_binbooking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedbinstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='bookedbinstatus',
            name='status_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
