# Generated by Django 4.2.3 on 2023-09-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0055_remove_bookedbinstatus_id_bookedbinstatus_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binbooking',
            name='booking_id',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
    ]
