# Generated by Django 4.2.3 on 2023-09-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0056_alter_binbooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedbinstatus',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='app32.binbooking'),
        ),
        migrations.AlterField(
            model_name='bookedbinstatus',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
