from collections import UserList
from django.contrib import admin
from .models import UserProfile
from .models import Event
from .models import Bin
admin.site.register(Event)
admin.site.register(UserProfile)


from django.contrib import admin


@admin.register(Bin)

class BinAdmin(admin.ModelAdmin):
    # Other admin options
    change_url = 'app32_bin_change'
    list_display = ('bin_id', 'title', 'size', 'capacity')
    search_fields = ('bin_id', 'title')
    list_filter = ('size', 'capacity')
    readonly_fields = ('bin_id',)  # Assuming bin_id is autogenerated

from .models import BinEvent

@admin.register(BinEvent)
class BinEventAdmin(admin.ModelAdmin):
    list_display = ('bin_id', 'title', 'size', 'capacity')
    search_fields = ('bin_id', 'title')
    list_filter = ('size', 'capacity')
    ordering = ('title',)









from django.contrib import admin
from .models import BinBooking

# Register the BinBooking model
class BinBookingAdmin(admin.ModelAdmin):
    from .models import BinBooking

class BinBookingAdmin(admin.ModelAdmin):
    list_display = ('id', 'user', 'bin', 'house_number', 'landmark', 'pin_code', 'bin_size', 'bin_capacity', 'collection_period')
    # You can customize the list display columns as needed

admin.site.register(BinBooking, BinBookingAdmin)

from .models import EventBooking

admin.site.register(EventBooking)

# binbookiedststus
from django.contrib import admin
from .models import BinBooking, BookedBinStatus
@admin.register(BookedBinStatus)
class BookedBinStatusAdmin(admin.ModelAdmin):
    list_display = ('status_id', 'booking', 'fill_level', 'created_at', 'updated_at')
    list_filter = ('fill_level', 'created_at', 'updated_at')
    list_per_page = 20


