# Generated by Django 4.2.3 on 2024-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0004_remove_like_user_profile_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('owners_shareholders_names', models.TextField()),
                ('vat_registration_number', models.CharField(max_length=20)),
                ('business_address', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('business_license_document', models.FileField(upload_to='business_licenses/')),
            ],
        ),
    ]
