# Generated by Django 4.2.3 on 2024-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0005_companyregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='password',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='business_license_document',
            field=models.FileField(upload_to='company_documents/'),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
