# Generated by Django 4.2.3 on 2024-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0006_companyregistration_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('document', models.FileField(upload_to='company_documents/')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
