# Generated by Django 4.2.3 on 2024-01-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0009_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organisation_chain', models.CharField(max_length=50)),
                ('tender_type', models.CharField(choices=[('open', 'Open Tender'), ('closed', 'Closed Tender')], max_length=50)),
                ('tender_category', models.CharField(choices=[('waste_disposal', 'Waste Disposal'), ('category2', 'Category 2'), ('category3', 'Category 3')], max_length=50)),
                ('reference_number', models.CharField(max_length=50)),
                ('closing_date', models.DateField()),
                ('bid_opening_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('offline', 'Offline Payment'), ('online', 'Online Payment')], max_length=50)),
            ],
        ),
    ]
