# Generated by Django 4.2.3 on 2024-02-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0010_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='tender_category',
            field=models.CharField(choices=[('waste_disposal', 'Waste Disposal')], max_length=50),
        ),
    ]
