# Generated by Django 4.2.3 on 2024-02-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0012_alter_companyregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyregistration',
            options={},
        ),
        migrations.AlterModelManagers(
            name='companyregistration',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='companyregistration',
            name='username',
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='password',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='vat_registration_number',
            field=models.CharField(max_length=20),
        ),
    ]
