# Generated by Django 4.2.3 on 2024-02-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0013_alter_companyregistration_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Seller',
        ),
    ]
