# Generated by Django 4.2.3 on 2024-02-04 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app322', '0016_companyapplyfortender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyapplyfortender',
            name='company',
        ),
        migrations.AddField(
            model_name='companyapplyfortender',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
