# Generated by Django 4.2.3 on 2024-02-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0017_remove_companyapplyfortender_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTender',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app322.companyapplyfortender')),
                ('approval_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedTender',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app322.companyapplyfortender')),
                ('rejection_date', models.DateField(auto_now_add=True)),
                ('rejection_reason', models.TextField()),
            ],
        ),
    ]
