# Generated by Django 4.2.3 on 2024-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0018_approvedtender_rejectedtender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recyclable_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('e_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hazardous_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('organic_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_category', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
