# Generated by Django 4.2.3 on 2024-02-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0019_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='tender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app322.tender'),
        ),
    ]
