# Generated by Django 4.2.3 on 2024-02-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0020_waste_tender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedtender',
            old_name='application',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='rejectedtender',
            old_name='application',
            new_name='registration',
        ),
    ]
