# Generated by Django 4.2.3 on 2024-02-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0024_remove_product_seller_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
