# Generated by Django 4.2.3 on 2024-02-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0027_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
