# Generated by Django 4.2.3 on 2024-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0028_remove_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('eemail', models.CharField(max_length=100)),
            ],
        ),
    ]
