# Generated by Django 4.2.3 on 2024-03-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0032_order_orderitem_order_products_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrival_date',
        ),
    ]
