# Generated by Django 4.2.3 on 2024-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app322', '0037_collectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='collection_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='recyclable_type',
            field=models.CharField(max_length=100),
        ),
    ]
